### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by nzk-tomo** [nzk-tomo/protospace-31124#1]
# URL
https://protospace-31124.herokuapp.com/

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①ユーザー名をクリックすると、別のユーザーの詳細ページに遷移する場合があります。
クリックしたユーザーの詳細ページに遷移するようにしましょう！**
※何回か試した所、同じユーザーが投稿したプロトタイプでも、遷移先のユーザー詳細ページが異なりました。


修正が完了しましたら、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by nzk-tomo** [comment]
修正しました

**Comment by mutorisa** [comment]
野月さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by nzk-tomo** [comment]
ありがとうございました！
